name: RuboCop
on:
  push:
    branches:
      - main
      - development
      - CI
  pull_request:
    branches:
      - main
      - development
      - CI
jobs:
  rubocop:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: '3.1.3'  # Adjust this to match your Ruby version

    - name: Install dependencies
      run: bundle install
    - name: migrate1
      run: rails db:create RAILS_ENV=test
    - name: migrate2
      run: rails db:migrate RAILS_ENV=test

    - name: Run Tests
      run: bundle exec rspec       

    - name: Run RuboCop
      run: bundle exec rubocop 
